### ISSUE TITLE
'simple_example' is not working with the latest changes in parent_id and parent_type

### ISSUE THREAD

**Issue by shraddhajain01** [terraform-google-modules/terraform-google-folders#11]
I get below error when I try to create 2 folders under one organization using the 'simple_example' code:

module.folders.google_folder.folders[0]: Creating...
module.folders.google_folder.folders[1]: Creating...

Error: Error creating folder 'shared-test' in 'organization/**********': googleapi: Error 400: Request contains an invalid argument., badRequest

  on ../../main.tf line 25, in resource "google_folder" "folders":
  25: resource "google_folder" "folders" {

Error: Error creating folder 'management_test' in 'organization/***********': googleapi: Error 400: Request contains an invalid argument., badRequest

  on ../../main.tf line 25, in resource "google_folder" "folders":
  25: resource "google_folder" "folders" {

**Comment by morgante** [comment]
Can you share your module config?

Note the parent_type in the example needs to be "organizations" not "organization."

**Comment by shraddhajain01** [comment]
Yes, changing it to 'organizations' worked. Thanks.
Please make changes in the description for 'parent_type' variable in variables.tf. It should be 'organizations' and 'reosurce' as 'resource'.

**Comment by morgante** [comment]
@averbuks Please update the variable description in the simple example.

**Comment by averbuks** [comment]
Description has been updated
