### ISSUE TITLE
unable to create Service account at org level in GCP to create the folder

### ISSUE THREAD

**Issue by SprintCT** [terraform-google-modules/terraform-google-folders#25]
Hi,

I unable to understand how to create Service account at org level in GCP to create the folder/project creation to working on this module. As per module i have to place file the credential path. Since i unable to create a service i unable to provide it.
Kindly assist me on this.

Example:
I got Admin access for org level. And i have created a member (not service account) and provide access to folder creator role and project create role. Now i don't know how to use this module.

**Comment by morgante** [comment]
As I understand it, your personal user account has admin access. In that case, you can run `gcloud auth application-default login` to authenticate Terraform and this module, as per the [Terraform docs](https://www.terraform.io/docs/providers/google/guides/provider_reference.html#credentials-1).

**Comment by SprintCT** [comment]
If it is automation by pipeline as code, May i know how i need to parse this credential file
