### ISSUE TITLE
Use different roles for the admins

### ISSUE THREAD

**Issue by lemoo5sg** [terraform-google-modules/terraform-google-folders#39]
### TL;DR

Unless I'm mistaken, the same roles list _(folder_admin_roles)_ will be deployed for the admins.
Objective here is to change the variables to allow having a different set of roles for each admin for each folder.

**Comment by g-awmalik** [comment]
@lemoo5sg - sorry for the delay. The `folder_admin_roles` is carefully curated to represent a folder admin. If you're looking to apply specific roles to a specific set of users, the [IAM](https://github.com/terraform-google-modules/terraform-google-iam) module may better fit your requirements.

**Comment by lemoo5sg** [comment]
@g-awmalik the point is that the module can create multiple folders and we can set differrent admins for each folder, which is great, however we are forced to apply the same roles to all the admins. This would be great to be able to change the assigned roles per folder as it is done for the admins lists

**Comment by lemoo5sg** [comment]
Up otherwise the bot will close the case ;)
