### ISSUE TITLE
Parent ID is complicated for nested folders

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-folders#6]
Currently, parent is specified using *both* the `parent_id` and `parent_type`.

This makes it challenging to nest folders because the *output* from this module is `folders/{id}` but the expected input is `{id}`.

We should converge so only `folders/{id}` is the input (and `parent_type` is deprecated).

**Comment by ludoo** [comment]
Morgante, how would you create folders with org as a parent then?

**Comment by ludoo** [comment]
Or are you saying the full `parent_type`/`parent_id` is th enew input?

**Comment by morgante** [comment]
I'm suggesting the full parent_type/parent_id as the new input.
